### PR TITLE
Optimize YOLOX

### LINKED ISSUE #9: Optimize yolox model
The current yolox model has many transpose layers inserted, so I would like to optimize it by following the steps below.

Why does onnx-tensorflow add Transpose layers for each Conv2D layer?
https://github.com/onnx/onnx-tensorflow/issues/782

```
I found the solution, perform following to convert form pytorch ---> tflite (NCHW ---> NHWC):

pytorch official export to onnx [N,C,H,W] ---> [N,C,H,W]
onnx conversion to open-vino IR format [N,C,H,W] ---> [N,C,H,W] (using openvino docker image)
open-vino-IR format to tensorflow format [N,C,H,W] ---> [N,H,W,C] (using openvino2tensorflow ⚡ 💡 docker image, see https://github.com/PINTO0309/openvino2tensorflow.git)
tensorflow format to tflite [N,H,W,C] ---> [N,H,W,C] 😄
```

OpenVino2Tensorflow
https://github.com/PINTO0309/openvino2tensorflow

Tutorial
https://qiita.com/PINTO/items/ed06e03eb5c007c2e102

### PR DESCRIPTION
**Pull request by zhaochow**
Resolve #9 

Add optimized version of YOLOX tiny TFLite with NHWC order natively, removing many Transpose layers

New YOLOX tiny TFLite model has already been uploaded to the server

### CODE REVIEW

**Comment by kyakuno** [comment]
@zhaochow Can you change model file name for previous user?

**Comment by kyakuno** [comment]
Overwriting the server model file causes past scripts to stop working. Therefore, please add .opt etc. to the file name and upload it.

**Comment by zhaochow** [comment]
@kyakuno 
> Overwriting the server model file causes past scripts to stop working. Therefore, please add .opt etc. to the file name and upload it.

I re-uploaded the old TFLite file to the server and updated the code to use the optimized version in the latest code

**Comment by kyakuno** [comment]
Optimize版の推論にはailia TFLite Runtime 1.1.1が必要。

**Review by kyakuno — APPROVED** [review]

**Pull request merged**
